/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Config.KoneksiDB;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anas
 */
public class PanelMahasiswa extends javax.swing.JPanel {

    public Connection con;

    public PanelMahasiswa() {
        initComponents();

        con = KoneksiDB.getConnection();

        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        FieldNim = new javax.swing.JTextField();
        NIM = new javax.swing.JLabel();
        FieldNama = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnSimpan = new javax.swing.JButton();
        BtnSimpan1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null },
                        { null, null },
                        { null, null },
                        { null, null }
                },
                new String[] {
                        "NIM", "Nama Lengkap"
                }));
        jScrollPane1.setViewportView(tableMahasiswa);
        if (tableMahasiswa.getColumnModel().getColumnCount() > 0) {
            tableMahasiswa.getColumnModel().getColumn(0).setMinWidth(150);
            tableMahasiswa.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        NIM.setText("NIM");

        LabelNama.setText("Nama");

        BtnTambah.setBackground(new java.awt.Color(102, 255, 51));
        BtnTambah.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setBackground(new java.awt.Color(102, 255, 51));
        BtnHapus.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnSimpan.setBackground(new java.awt.Color(0, 51, 102));
        BtnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnSimpan1.setBackground(new java.awt.Color(0, 51, 102));
        BtnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        BtnSimpan1.setText("Edit");
        BtnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpan1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setText("Daftar Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(BtnSimpan1))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(BtnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(BtnHapus, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(12, 12, 12))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(LabelNama)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(FieldNim,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(FieldNama)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(NIM)
                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addContainerGap()))))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(NIM, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(FieldNim, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(LabelNama)
                                                .addGap(7, 7, 7)
                                                .addComponent(FieldNama, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(BtnTambah)
                                                        .addComponent(BtnHapus))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(BtnSimpan)
                                                        .addComponent(BtnSimpan1))
                                                .addContainerGap(145, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE))));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSimpan1ActionPerformed
        editData(); // TODO add your handling code here:
    }// GEN-LAST:event_BtnSimpan1ActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnHapusActionPerformed
        hapusData();
    }

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSimpanActionPerformed
        simpanData();
        clearForm();
    }

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnTambahActionPerformed
        tambahData();
        clearForm();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnSimpan1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JTextField FieldNama;
    private javax.swing.JTextField FieldNim;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMahasiswa;
    // End of variables declaration//GEN-END:variables

    public void loadData() {
        DefaultTableModel model = (DefaultTableModel) tableMahasiswa.getModel();
        model.setRowCount(0);

        try {
            String sql = "SELECT * FROM mahasiswa";
            try (PreparedStatement st = con.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    String nim = rs.getString("NIM");
                    String nama = rs.getString("Nama");

                    model.addRow(new Object[] { nim, nama });
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load data: " + e.getMessage());
        }
    }

    public void tambahData() {
        String nim = FieldNim.getText();
        String nama = FieldNama.getText();

        String sql = "INSERT INTO mahasiswa (NIM, Nama) VALUES (?, ?)";

        if (nim.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM dan Nama harus diisi");
            return;

        } else {
            try {
                try (PreparedStatement st = con.prepareStatement(sql)) {
                    st.setString(1, nim);
                    st.setString(2, nama);

                    st.executeUpdate();
                }

                loadData();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "NIM sudah ada ");
            }
        }
    }

    public void editData() {
        int selectedRow = tableMahasiswa.getSelectedRow();
        if (selectedRow != -1) {
            String fnim = (String) tableMahasiswa.getValueAt(selectedRow, 0);
            String fnama = (String) tableMahasiswa.getValueAt(selectedRow, 1);
            FieldNim.setText(fnim);
            FieldNama.setText(fnama);
        }

    }

    public void simpanData() {
        try {
            String nim = FieldNim.getText();
            String nama = FieldNama.getText();
            String sql = "UPDATE mahasiswa SET Nama = ? WHERE NIM = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, nama);
            st.setString(2, nim);
            st.executeUpdate();
            loadData();
        } catch (Exception e) {

        }
    }

    public void hapusData() {
        try {
            int selectedRow = tableMahasiswa.getSelectedRow();
            if (selectedRow != -1) {
                String nim = (String) tableMahasiswa.getValueAt(selectedRow, 0);
                String sql = "DELETE FROM mahasiswa WHERE NIM = ?";
                PreparedStatement st = con.prepareStatement(sql);
                st.setString(1, nim);
                st.executeUpdate();
                loadData();
            }
        } catch (Exception e) {

        }
    }

    public void clearForm() {
        FieldNim.setText("");
        FieldNama.setText("");
    }
}